package com.example.huaweicalc;

import android.app.*;import android.os.*;import android.content.*;import android.widget.*;import android.text.*;import java.util.*;

public class MainActivity extends Activity{
 EditText txtImei,txtFlash,txtV1,txtV2,txtV201; TextView lblStatus;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);txtImei=findViewById(R.id.txtImei);txtFlash=findViewById(R.id.txtFlash);txtV1=findViewById(R.id.txtV1);txtV2=findViewById(R.id.txtV2);txtV201=findViewById(R.id.txtV201);lblStatus=findViewById(R.id.lblStatus);findViewById(R.id.btnCalculate).setOnClickListener(v->calc());findViewById(R.id.btnClear).setOnClickListener(v->clear());findViewById(R.id.btnCopyAll).setOnClickListener(v->copyAll());findViewById(R.id.btnCopyFlash).setOnClickListener(v->copy(txtFlash.getText().toString()));findViewById(R.id.btnCopyV1).setOnClickListener(v->copy(txtV1.getText().toString()));findViewById(R.id.btnCopyV2).setOnClickListener(v->copy(txtV2.getText().toString()));findViewById(R.id.btnCopyV201).setOnClickListener(v->copy(txtV201.getText().toString()));txtImei.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){} public void onTextChanged(CharSequence s,int st,int b,int c){lblStatus.setText(s.length()==15?"Ready to calculate":"IMEI must be 15 digits");} public void afterTextChanged(Editable e){}});} 
 void calc(){String imei=txtImei.getText().toString().trim();if(imei.length()!=15||!imei.matches("\\d+")){Toast.makeText(this,"Please enter valid 15-digit IMEI",Toast.LENGTH_LONG).show();return;}try{CodeResult r=HuaweiCalc.CalculateAll(imei);txtFlash.setText(r.flash);txtV1.setText(r.v1);txtV2.setText(r.v2);txtV201.setText(r.v201);lblStatus.setText("Calculated");}catch(Exception e){Toast.makeText(this,"Calculation failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void clear(){txtImei.setText("");txtFlash.setText("");txtV1.setText("");txtV2.setText("");txtV201.setText("");lblStatus.setText("Ready");}
 void copy(String s){if(s==null||s.length()==0)return;((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("code",s));lblStatus.setText("Copied");}
 void copyAll(){String s="IMEI: "+txtImei.getText()+"\nFlash Code: "+txtFlash.getText()+"\nV1 Code: "+txtV1.getText()+"\nV2 Code: "+txtV2.getText()+"\nV201 Code: "+txtV201.getText();copy(s);} }
